name: Validate Changes

on:
  pull_request: 
    branches:
      - master
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NuGet
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Authenticate to GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" \
                    --name "dmcphgh" \
                    --username "${{ github.repository_owner }}" \
                    --password "${{secrets.DEPLOY_KEY}}" \
                    --store-password-in-clear-text
      - name: Build and Restore
        run: |
          dotnet restore
          dotnet build ./Vectra.VM.sln --configuration Release --no-restore