name: Release Package
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

permissions:
  packages: write
  contents: write
  issues: write

jobs:
  build:
    if: >
      startsWith(github.ref, 'refs/heads/master') &&
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
    - uses: DuncanMcPherson/vectra-workflows@master
      with:
        app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
        deploy-key: ${{ secrets.DEPLOY_KEY }}
