name: Release Package
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

permissions:
  packages: write
  contents: write
  issues: write

jobs:
  build:
    if: >
      startsWith(github.ref, 'refs/heads/master') &&
      !contains(github.event.head_commit.message, '[skip ci]')
    uses: DuncanMcPherson/vectra-workflows/.github/workflows/release.yml@master
    secrets: inherit
